name: icm_rag_env
channels:
  - pyg
  - huggingface
  - defaults
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.1=h7b32b05_0
  - pip=25.0.1=pyh8b19718_0
  - python=3.11.11=h9e4cc4f_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=75.8.2=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - argparse==1.4.0
      - certifi==2025.1.31
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - distlib==0.3.9
      - filelock==3.18.0
      - identify==2.6.9
      - idna==3.10
      - nodeenv==1.9.1
      - numpy==2.2.3
      - pandas==2.2.3
      - platformdirs==4.3.7
      - pre-commit==4.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - requests==2.32.3
      - six==1.17.0
      - tzdata==2025.1
      - urllib3==2.3.0
      - virtualenv==20.30.0
